Repository RuchithaVirashan/bookHub, pull requests merged in 2022-10, with the labels that each got.

#26 updated
  README.md
Labels: documentation, hacktoberfest-accepted

#27 Add files via upload
  addItemList.php
  custom.css
Labels: hacktoberfest-accepted

#28 update database
  database/admins.sql
Labels: hacktoberfest-accepted

#30 adding item delete process
  delete_process.php
Labels: hacktoberfest-accepted

#32 add item description
  itemDescription.php
Labels: hacktoberfest-accepted

#33 Add database config to admins
  admin_db_conn.php
Labels: hacktoberfest-accepted

#34 Add user profile page
  user_profile.php
Labels: hacktoberfest-accepted

#35 Add script files to the repo
  head.php
  script.php
Labels: hacktoberfest-accepted

#36 Add admin profile page
  admin_profile.php
Labels: hacktoberfest-accepted

#37 change veriable
  addItemList.php
  admin_home.php
Labels: hacktoberfest-accepted

#38 bug update
  authorDes.php
  cat-items.php
Labels: hacktoberfest-accepted

#39 delete option
  cat-items.php
Labels: hacktoberfest-accepted

#41 dba connecting
  cat-items.php
Labels: hacktoberfest-accepted

#42 add code of conduct documentation
  Code_Of_Conduct.md
Labels: good first issue, hacktoberfest-accepted, gj
